schemaVersion = 1

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256

    [hotkeys.app.leaderMode]
    carbonKeyCode = 111
    carbonModifiers = 0

[[leaderMode.bindings]]
iconPath = 'cat'
key = 'a'
label = 'Apps'

    [[leaderMode.bindings.children]]
    key = 'b'
    url = 'tuna://run/path.%252FApplications%252FZen.app/Open'

    [[leaderMode.bindings.children]]
    key = 'c'
    url = 'tuna://run/path.%252FSystem%252FApplications%252FCalendar.app/Open'

    [[leaderMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/path.%252FApplications%252FSpotify.app/Open'

    [[leaderMode.bindings.children]]
    key = 'n'
    url = 'tuna://run/path.%252FApplications%252FObsidian.app/Open'

    [[leaderMode.bindings.children]]
    key = 't'
    url = 'tuna://run/path.%252FApplications%252FGhostty.app/Open'

[[leaderMode.bindings]]
iconPath = 'safari'
key = 'b'
label = 'Browsers'

    [[leaderMode.bindings.children]]
    key = 'c'
    url = 'tuna://run/path.%252FApplications%252FGoogle%2520Chrome.app/Open'

    [[leaderMode.bindings.children]]
    key = 'h'
    url = 'tuna://run/path.%252FApplications%252FHelium.app/Open'

    [[leaderMode.bindings.children]]
    key = 'o'
    url = 'tuna://run/path.%252FApplications%252FOrion.app/Open'

    [[leaderMode.bindings.children]]
    key = 'z'
    url = 'tuna://run/path.%252FApplications%252FZen.app/Open'

[[leaderMode.bindings]]
iconPath = 'camera.metering.center.weighted.average'
key = 'c'
label = 'Capture'

    [[leaderMode.bindings.children]]
    key = 'a'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FAayush9029%252Fcleanshotx%252Fcapture-area/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'f'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FAayush9029%252Fcleanshotx%252Fcapture-fullscreen/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'v'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FAayush9029%252Fcleanshotx%252Frecord-screen/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'w'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252FAayush9029%252Fcleanshotx%252Fcapture-window/Open%20URL'

[[leaderMode.bindings]]
key = 'enter'
label = 'Terminal'
url = 'tuna://run/path.%252FApplications%252FGhostty.app/Open'

[[leaderMode.bindings]]
iconPath = 'uiwindow.split.2x1'
key = 'f'
label = 'Window'

    [[leaderMode.bindings.children]]
    key = '3'
    label = 'Thirds'

        [[leaderMode.bindings.children.children]]
        key = '2'
        label = 'Two thirds'

            [[leaderMode.bindings.children.children.children]]
            key = 'h'
            label = 'First two thirds'
            url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=first-two-thirds/Open%20URL'

            [[leaderMode.bindings.children.children.children]]
            key = 'l'
            label = 'Last two thirds'
            url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=last-two-thirds/Open%20URL'

        [[leaderMode.bindings.children.children]]
        key = 'c'
        label = 'Center third'
        url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=center-third/Open%20URL'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'First third'
        url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=first-third/Open%20URL'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'Last third'
        url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=last-third/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'c'
    label = 'Center'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=center/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'f'
    label = 'Full screen'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=maximize/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'h'
    label = 'Left'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=left-half/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'H'
    label = 'Max height'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=maximize-height/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'l'
    label = 'Right'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=right-half/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'n'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=first-third/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'o'
    url = 'tuna://run/url.rectangle-pro:%252F%252Fexecute-action%253Fname=last-two-thirds/Open%20URL'

[[leaderMode.bindings]]
iconPath = 'bookmark'
key = 'g'
label = 'Folders'

    [[leaderMode.bindings.children]]
    key = 'a'
    url = 'tuna://run/path.%252FApplications/Open'

    [[leaderMode.bindings.children]]
    key = 'd'
    url = 'tuna://run/path.%252FUsers%252Fattamusc%252FDownloads/Open'

    [[leaderMode.bindings.children]]
    key = 'h'
    url = 'tuna://run/path.%252FUsers%252Fattamusc/Open'

[[leaderMode.bindings]]
iconPath = 'sparkles'
key = 'l'
label = 'LLMs'

    [[leaderMode.bindings.children]]
    key = 'a'
    label = 'Claude'
    url = 'tuna://run/path.%252FApplications%252FClaude.app/Open'

    [[leaderMode.bindings.children]]
    key = 'c'
    url = 'tuna://run/path.%252FApplications%252FChatGPT.app/Open'

[[leaderMode.bindings]]
iconPath = 'message'
key = 'm'
label = 'Messaging'

    [[leaderMode.bindings.children]]
    key = 'd'
    url = 'tuna://run/path.%252FApplications%252FDiscord.app/Open'

    [[leaderMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

    [[leaderMode.bindings.children]]
    key = 's'
    url = 'tuna://run/path.%252FApplications%252FSlack.app/Open'

[[leaderMode.bindings]]
iconPath = 'diamond'
key = 'o'
label = 'Obsidian'

    [[leaderMode.bindings.children]]
    key = 'd'
    label = 'Daily'
    url = 'tuna://run/url.obsidian:%252F%252Fdaily/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'o'
    label = 'Open'
    url = 'tuna://run/path.%252FApplications%252FObsidian.app/Open'

[[leaderMode.bindings]]
iconPath = 'character.textbox'
key = 'r'
label = 'Raycast'

    [[leaderMode.bindings.children]]
    key = 'c'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Fopen-camera/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'e'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Femoji-symbols%252Fsearch-emoji-symbols/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 'p'
    url = 'tuna://run/url.raycast:%252F%252Fconfetti/Open%20URL'

[[leaderMode.bindings]]
iconPath = 'laptopcomputer'
key = 's'
label = 'System'

    [[leaderMode.bindings.children]]
    key = 'l'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Flock-screen/Open%20URL'

    [[leaderMode.bindings.children]]
    key = 's'
    url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Fsystem%252Fsleep/Open%20URL'

[settings]
backspaceBehavior = 'deleteCharacters'
leaderModeCheatsheetBehavior = 'always'
leaderModeThemeStyle = 'breadcrumb'
screenPreference = 'primary'
themeIdentifier = 'com.brnbw.tuna.themes.default'
typingTimeoutDuration = 0.94999999999999996

[[smartLinks.entries]]
enabled = true
name = 'bing'
template = 'https://www.bing.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'ddg'
template = 'https://duckduckgo.com/?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'g'
template = 'https://www.google.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'gh'
template = 'https://github.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'ghr'
template = 'https://github.com/{{input|raw}}'

[[smartLinks.entries]]
enabled = true
name = 'so'
template = 'https://stackoverflow.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'wiki'
template = 'https://en.wikipedia.org/wiki/Special:Search?search={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'yt'
template = 'https://www.youtube.com/results?search_query={{input}}'